# -*- coding: utf-8 -*-
"""Shiplimentb-Delay-Classification-predictin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EwGm5unrCkGE-G2h0VhleknF2KMnCB-f
"""

# Import libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load dataset

df = pd.read_csv('/content/shipping_data_0.csv')

# Show first 5 rows

df.head()

# Dataset information

df.info()

# Check missing values

df.isnull().sum()

# Check target column values

df['on_time'].value_counts()

# Drop ID column if present

# The 'ID' column does not exist in the dataframe, so this line is not needed.
# df.drop(['ID'], axis=1, inplace=True)

df.head()

# Convert categorical columns into numeric

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

categorical_cols = ['origin_warehouse', 'destination_store', 'product', 'driver_identifier']

for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

df.head()

# Features and target

X = df.drop('on_time', axis=1)

y = df['on_time']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

from sklearn.ensemble import RandomForestClassifier

# Create model

model = RandomForestClassifier()

# Train model

model.fit(X_train, y_train)

# Predictions

y_pred = model.predict(X_test)

y_pred[:10]

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

from sklearn.metrics import confusion_matrix
import seaborn as sns

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,4))

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')

plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

# Feature importance

importance = model.feature_importances_

features = X.columns

importance_df = pd.DataFrame({
    'Feature': features,
    'Importance': importance
})

importance_df = importance_df.sort_values(
    by='Importance',
    ascending=False
)

importance_df

plt.figure(figsize=(10,6))

plt.barh(
    importance_df['Feature'],
    importance_df['Importance']
)

plt.xlabel("Importance")
plt.ylabel("Features")

plt.title("Feature Importance")

plt.show()

import pickle

# Save model

with open('shipment_model.pkl', 'wb') as file:
    pickle.dump(model, file)

print("Model Saved Successfully")

!pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import numpy as np
# import pickle
# import matplotlib.pyplot as plt
# 
# # Load model
# 
# with open('shipment_model.pkl', 'rb') as file:
#     model = pickle.load(file)
# 
# # Title
# 
# st.title("Shipment Delay Prediction Dashboard")
# 
# st.write("Predict whether shipment will arrive on time or be delayed.")
# 
# # User Inputs
# 
# warehouse_block = st.selectbox(
#     "Warehouse Block",
#     [0,1,2,3,4]
# )
# 
# mode_of_shipment = st.selectbox(
#     "Mode of Shipment",
#     [0,1,2]
# )
# 
# customer_care_calls = st.slider(
#     "Customer Care Calls",
#     0,
#     10,
#     3
# )
# 
# customer_rating = st.slider(
#     "Customer Rating",
#     1,
#     5,
#     3
# )
# 
# cost_of_product = st.number_input(
#     "Cost of Product",
#     0,
#     1000,
#     200
# )
# 
# prior_purchases = st.slider(
#     "Prior Purchases",
#     0,
#     20,
#     5
# )
# 
# product_importance = st.selectbox(
#     "Product Importance",
#     [0,1,2]
# )
# 
# gender = st.selectbox(
#     "Gender",
#     [0,1]
# )
# 
# discount_offered = st.slider(
#     "Discount Offered",
#     0,
#     100,
#     10
# )
# 
# weight_in_gms = st.number_input(
#     "Weight in Grams",
#     100,
#     10000,
#     3000
# )
# 
# # Prediction Button
# 
# if st.button("Predict Shipment Status"):
# 
#     input_data = np.array([[
#         warehouse_block,
#         mode_of_shipment,
#         customer_care_calls,
#         customer_rating,
#         cost_of_product,
#         prior_purchases,
#         product_importance,
#         gender,
#         discount_offered,
#         weight_in_gms
#     ]])
# 
#     prediction = model.predict(input_data)
# 
#     if prediction[0] == 1:
#         st.success("Shipment will arrive on time.")
#     else:
#         st.error("Shipment may be delayed.")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# 
# streamlit
# pandas
# numpy
# matplotlib
# scikit-learn
# seaborn